name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Change to project directory
      run: cd path/to/your/project
      # Reemplaza 'path/to/your/project' con la ruta real al directorio del proyecto

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore ./path/to/your/project/YourProject.csproj
      # Reemplaza './path/to/your/project/YourProject.csproj' con la ruta real al archivo de proyecto

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: app
    - name: Output contents
      run: ls
    - name: Deploy to Server
      run: |
        echo "Deploy"
